### ISSUE TITLE
Build Primitive Enclosure Stand.

### ISSUE THREAD

**Issue by JonathanFager** [BryggansBryggeri/mechanical#10]
- [x] Order steel
- [x] Cut to size
- [x] Miter
- [x] Weld
- [x] Drill and find bolts for enclosure
- [x] Adjustable Feet.
- [x] Paint

**Comment by JonathanFager** [comment]
First drawing consisting of steel stand made by 40x40 steel square tubing.
[ställning.pdf](https://github.com/BryggansBryggeri/mechanical/files/3752596/stallning.pdf)

**Comment by jackonelli** [comment]
I agree this is a good fit for the enclosure. But how does it fit with the vessels???

**Comment by JonathanFager** [comment]
Flapdisc, feet and paint purchased.

**Comment by JonathanFager** [comment]
All done!
